allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.google.com' }
    }
}

subprojects {
    configurations.all {
        resolutionStrategy {
            force 'com.arthenica:ffmpeg-kit-https:6.0.LTS'
            force 'com.arthenica:ffmpeg-kit-min:6.0.LTS'
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
